'// <auto-generated />
'// This file was generated by a T4 template.
'// Don't change it directly as your change would get overwritten.  Instead, make changes
'// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

'// Make sure the compiler doesn't complain about missing Xml comments
'#pragma warning disable 1591
#region "T4MVC"

Imports System
Imports System.Diagnostics
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.Linq
Imports System.Runtime.CompilerServices
Imports System.Web
Imports System.Web.Hosting
Imports System.Web.Mvc
Imports System.Web.Mvc.Ajax
Imports System.Web.Mvc.Html
Imports System.Web.Routing
Imports MvcApplicationVBT4MVC.T4MVC
    Public Partial Class AccountController
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
		Public Sub New()
		End Sub
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
		Protected Sub New(d as Dummy)
		End Sub

		<GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
		Protected Overloads Function RedirectToAction(result as ActionResult) as RedirectToRouteResult
			Dim callInfo = result.GetT4MVCResult()
            Return RedirectToRoute(callInfo.RouteValueDictionary)
		End Function

		<GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
		Protected Overloads Function RedirectToActionPermanent(result as ActionResult) as RedirectToRouteResult
			Dim callInfo = result.GetT4MVCResult()
            Return RedirectToRoutePermanent(callInfo.RouteValueDictionary)
		End Function

        <NonAction>
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Overridable Function Login() as System.Web.Mvc.ActionResult
            Return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login)
        End Function
        <NonAction>
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Overridable Function Disassociate() as System.Web.Mvc.ActionResult
            Return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Disassociate)
        End Function
        <NonAction>
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Overridable Function Manage() as System.Web.Mvc.ActionResult
            Return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Manage)
        End Function
        <NonAction>
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Overridable Function ExternalLogin() as System.Web.Mvc.ActionResult
            Return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalLogin)
        End Function
        <NonAction>
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Overridable Function ExternalLoginCallback() as System.Web.Mvc.ActionResult
            Return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalLoginCallback)
        End Function
        <NonAction>
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Overridable Function ExternalLoginConfirmation() as System.Web.Mvc.ActionResult
            Return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalLoginConfirmation)
        End Function
        <NonAction>
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Overridable Function ExternalLoginsList() as System.Web.Mvc.ActionResult
            Return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalLoginsList)
        End Function

        <GeneratedCode("T4MVC", "2.0")>
		Public ReadOnly Property Actions As AccountController
			Get
				Return MVC.Account
			End Get
		End Property
        <GeneratedCode("T4MVC", "2.0")>
		Public ReadOnly Area As String = ""
        <GeneratedCode("T4MVC", "2.0")>
		Public ReadOnly Name As String = "Account"
        <GeneratedCode("T4MVC", "2.0")>
		Public Const NameConst As String = "Account"

		Shared ReadOnly s_actions As ActionNamesClass = new ActionNamesClass()
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
		Public ReadOnly Property ActionNames As ActionNamesClass
			Get
				Return s_actions
			End Get
		End Property

        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Class ActionNamesClass
            Public ReadOnly Login As String = "Login"
            Public ReadOnly LogOff As String = "LogOff"
            Public ReadOnly Register As String = "Register"
            Public ReadOnly Disassociate As String = "Disassociate"
            Public ReadOnly Manage As String = "Manage"
            Public ReadOnly ExternalLogin As String = "ExternalLogin"
            Public ReadOnly ExternalLoginCallback As String = "ExternalLoginCallback"
            Public ReadOnly ExternalLoginConfirmation As String = "ExternalLoginConfirmation"
            Public ReadOnly ExternalLoginFailure As String = "ExternalLoginFailure"
            Public ReadOnly ExternalLoginsList As String = "ExternalLoginsList"
            Public ReadOnly RemoveExternalLogins As String = "RemoveExternalLogins"
        End Class

        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Class ActionNameConstants
            Public Const Login As String = "Login"
            Public Const LogOff As String = "LogOff"
            Public Const Register As String = "Register"
            Public Const Disassociate As String = "Disassociate"
            Public Const Manage As String = "Manage"
            Public Const ExternalLogin As String = "ExternalLogin"
            Public Const ExternalLoginCallback As String = "ExternalLoginCallback"
            Public Const ExternalLoginConfirmation As String = "ExternalLoginConfirmation"
            Public Const ExternalLoginFailure As String = "ExternalLoginFailure"
            Public Const ExternalLoginsList As String = "ExternalLoginsList"
            Public Const RemoveExternalLogins As String = "RemoveExternalLogins"
        End Class


        Public Shared ReadOnly s_params_Login As ActionParamsClass_Login = new ActionParamsClass_Login()
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public ReadOnly Property LoginParams As ActionParamsClass_Login
			Get
				Return s_params_Login
			End Get
		End Property
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Class ActionParamsClass_Login
            Public ReadOnly returnUrl As String = "returnUrl"
            Public ReadOnly model As String = "model"
        End Class
        Public Shared ReadOnly s_params_Register As ActionParamsClass_Register = new ActionParamsClass_Register()
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public ReadOnly Property RegisterParams As ActionParamsClass_Register
			Get
				Return s_params_Register
			End Get
		End Property
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Class ActionParamsClass_Register
            Public ReadOnly model As String = "model"
        End Class
        Public Shared ReadOnly s_params_Disassociate As ActionParamsClass_Disassociate = new ActionParamsClass_Disassociate()
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public ReadOnly Property DisassociateParams As ActionParamsClass_Disassociate
			Get
				Return s_params_Disassociate
			End Get
		End Property
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Class ActionParamsClass_Disassociate
            Public ReadOnly provider As String = "provider"
            Public ReadOnly providerUserId As String = "providerUserId"
        End Class
        Public Shared ReadOnly s_params_Manage As ActionParamsClass_Manage = new ActionParamsClass_Manage()
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public ReadOnly Property ManageParams As ActionParamsClass_Manage
			Get
				Return s_params_Manage
			End Get
		End Property
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Class ActionParamsClass_Manage
            Public ReadOnly message As String = "message"
            Public ReadOnly model As String = "model"
        End Class
        Public Shared ReadOnly s_params_ExternalLogin As ActionParamsClass_ExternalLogin = new ActionParamsClass_ExternalLogin()
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public ReadOnly Property ExternalLoginParams As ActionParamsClass_ExternalLogin
			Get
				Return s_params_ExternalLogin
			End Get
		End Property
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Class ActionParamsClass_ExternalLogin
            Public ReadOnly provider As String = "provider"
            Public ReadOnly returnUrl As String = "returnUrl"
        End Class
        Public Shared ReadOnly s_params_ExternalLoginCallback As ActionParamsClass_ExternalLoginCallback = new ActionParamsClass_ExternalLoginCallback()
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public ReadOnly Property ExternalLoginCallbackParams As ActionParamsClass_ExternalLoginCallback
			Get
				Return s_params_ExternalLoginCallback
			End Get
		End Property
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Class ActionParamsClass_ExternalLoginCallback
            Public ReadOnly returnUrl As String = "returnUrl"
        End Class
        Public Shared ReadOnly s_params_ExternalLoginConfirmation As ActionParamsClass_ExternalLoginConfirmation = new ActionParamsClass_ExternalLoginConfirmation()
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public ReadOnly Property ExternalLoginConfirmationParams As ActionParamsClass_ExternalLoginConfirmation
			Get
				Return s_params_ExternalLoginConfirmation
			End Get
		End Property
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Class ActionParamsClass_ExternalLoginConfirmation
            Public ReadOnly model As String = "model"
            Public ReadOnly returnUrl As String = "returnUrl"
        End Class
        Public Shared ReadOnly s_params_ExternalLoginsList As ActionParamsClass_ExternalLoginsList = new ActionParamsClass_ExternalLoginsList()
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public ReadOnly Property ExternalLoginsListParams As ActionParamsClass_ExternalLoginsList
			Get
				Return s_params_ExternalLoginsList
			End Get
		End Property
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
        Public Class ActionParamsClass_ExternalLoginsList
            Public ReadOnly returnUrl As String = "returnUrl"
        End Class
		Public Shared Readonly s_views as ViewsClass = new ViewsClass()
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
		Public ReadOnly Property Views as ViewsClass
			Get
				Return s_views
			End Get
		End Property

		<GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
		Public Class ViewsClass
            Shared ReadOnly s_ViewNames as _ViewNamesClass = new _ViewNamesClass()
            Public ReadOnly Property ViewNames as _ViewNamesClass
            	Get
            		Return s_ViewNames
            	End Get
            End Property
            
            Public Class _ViewNamesClass
                Public ReadOnly _ChangePasswordPartial As String = "_ChangePasswordPartial"
                Public ReadOnly _ExternalLoginsListPartial As String = "_ExternalLoginsListPartial"
                Public ReadOnly _RemoveExternalLoginsPartial As String = "_RemoveExternalLoginsPartial"
                Public ReadOnly _SetPasswordPartial As String = "_SetPasswordPartial"
                Public ReadOnly ExternalLoginConfirmation As String = "ExternalLoginConfirmation"
                Public ReadOnly ExternalLoginFailure As String = "ExternalLoginFailure"
                Public ReadOnly Login As String = "Login"
                Public ReadOnly Manage As String = "Manage"
                Public ReadOnly Register As String = "Register"
            End Class
            Public ReadOnly _ChangePasswordPartial As String = "~/Views/Account/_ChangePasswordPartial.vbhtml"
            Public ReadOnly _ExternalLoginsListPartial As String = "~/Views/Account/_ExternalLoginsListPartial.vbhtml"
            Public ReadOnly _RemoveExternalLoginsPartial As String = "~/Views/Account/_RemoveExternalLoginsPartial.vbhtml"
            Public ReadOnly _SetPasswordPartial As String = "~/Views/Account/_SetPasswordPartial.vbhtml"
            Public ReadOnly ExternalLoginConfirmation As String = "~/Views/Account/ExternalLoginConfirmation.vbhtml"
            Public ReadOnly ExternalLoginFailure As String = "~/Views/Account/ExternalLoginFailure.vbhtml"
            Public ReadOnly Login As String = "~/Views/Account/Login.vbhtml"
            Public ReadOnly Manage As String = "~/Views/Account/Manage.vbhtml"
            Public ReadOnly Register As String = "~/Views/Account/Register.vbhtml"
        End Class
    End Class


	<GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
	Public Partial Class T4MVC_AccountController
	Inherits AccountController
		Public Sub New()
			MyBase.New(Dummy.Instance)
		End Sub
		Partial Private Sub LoginOverride(callInfo As T4MVC_System_Web_Mvc_ActionResult, returnUrl As String)

		End Sub
        Public Overrides Function Login(returnUrl As String) as System.Web.Mvc.ActionResult 
            Dim callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login)
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl)
            LoginOverride(callInfo, returnUrl)
            Return callInfo
        End Function

		Partial Private Sub LoginOverride(callInfo As T4MVC_System_Web_Mvc_ActionResult, model As MvcApplicationVBT4MVC.LoginModel, returnUrl As String)

		End Sub
        Public Overrides Function Login(model As MvcApplicationVBT4MVC.LoginModel, returnUrl As String) as System.Web.Mvc.ActionResult 
            Dim callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login)
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model)
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl)
            LoginOverride(callInfo, model, returnUrl)
            Return callInfo
        End Function

		Partial Private Sub LogOffOverride(callInfo As T4MVC_System_Web_Mvc_ActionResult)

		End Sub
        Public Overrides Function LogOff() as System.Web.Mvc.ActionResult 
            Dim callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogOff)
            LogOffOverride(callInfo)
            Return callInfo
        End Function

		Partial Private Sub RegisterOverride(callInfo As T4MVC_System_Web_Mvc_ActionResult)

		End Sub
        Public Overrides Function Register() as System.Web.Mvc.ActionResult 
            Dim callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register)
            RegisterOverride(callInfo)
            Return callInfo
        End Function

		Partial Private Sub RegisterOverride(callInfo As T4MVC_System_Web_Mvc_ActionResult, model As MvcApplicationVBT4MVC.RegisterModel)

		End Sub
        Public Overrides Function Register(model As MvcApplicationVBT4MVC.RegisterModel) as System.Web.Mvc.ActionResult 
            Dim callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register)
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model)
            RegisterOverride(callInfo, model)
            Return callInfo
        End Function

		Partial Private Sub DisassociateOverride(callInfo As T4MVC_System_Web_Mvc_ActionResult, provider As String, providerUserId As String)

		End Sub
        Public Overrides Function Disassociate(provider As String, providerUserId As String) as System.Web.Mvc.ActionResult 
            Dim callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Disassociate)
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "provider", provider)
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "providerUserId", providerUserId)
            DisassociateOverride(callInfo, provider, providerUserId)
            Return callInfo
        End Function

		Partial Private Sub ManageOverride(callInfo As T4MVC_System_Web_Mvc_ActionResult, message As MvcApplicationVBT4MVC.AccountController.ManageMessageId?)

		End Sub
        Public Overrides Function Manage(message As MvcApplicationVBT4MVC.AccountController.ManageMessageId?) as System.Web.Mvc.ActionResult 
            Dim callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Manage)
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "message", message)
            ManageOverride(callInfo, message)
            Return callInfo
        End Function

		Partial Private Sub ManageOverride(callInfo As T4MVC_System_Web_Mvc_ActionResult, model As MvcApplicationVBT4MVC.LocalPasswordModel)

		End Sub
        Public Overrides Function Manage(model As MvcApplicationVBT4MVC.LocalPasswordModel) as System.Web.Mvc.ActionResult 
            Dim callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Manage)
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model)
            ManageOverride(callInfo, model)
            Return callInfo
        End Function

		Partial Private Sub ExternalLoginOverride(callInfo As T4MVC_System_Web_Mvc_ActionResult, provider As String, returnUrl As String)

		End Sub
        Public Overrides Function ExternalLogin(provider As String, returnUrl As String) as System.Web.Mvc.ActionResult 
            Dim callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalLogin)
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "provider", provider)
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl)
            ExternalLoginOverride(callInfo, provider, returnUrl)
            Return callInfo
        End Function

		Partial Private Sub ExternalLoginCallbackOverride(callInfo As T4MVC_System_Web_Mvc_ActionResult, returnUrl As String)

		End Sub
        Public Overrides Function ExternalLoginCallback(returnUrl As String) as System.Web.Mvc.ActionResult 
            Dim callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalLoginCallback)
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl)
            ExternalLoginCallbackOverride(callInfo, returnUrl)
            Return callInfo
        End Function

		Partial Private Sub ExternalLoginConfirmationOverride(callInfo As T4MVC_System_Web_Mvc_ActionResult, model As MvcApplicationVBT4MVC.RegisterExternalLoginModel, returnUrl As String)

		End Sub
        Public Overrides Function ExternalLoginConfirmation(model As MvcApplicationVBT4MVC.RegisterExternalLoginModel, returnUrl As String) as System.Web.Mvc.ActionResult 
            Dim callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalLoginConfirmation)
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model)
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl)
            ExternalLoginConfirmationOverride(callInfo, model, returnUrl)
            Return callInfo
        End Function

		Partial Private Sub ExternalLoginFailureOverride(callInfo As T4MVC_System_Web_Mvc_ActionResult)

		End Sub
        Public Overrides Function ExternalLoginFailure() as System.Web.Mvc.ActionResult 
            Dim callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalLoginFailure)
            ExternalLoginFailureOverride(callInfo)
            Return callInfo
        End Function

		Partial Private Sub ExternalLoginsListOverride(callInfo As T4MVC_System_Web_Mvc_ActionResult, returnUrl As String)

		End Sub
        Public Overrides Function ExternalLoginsList(returnUrl As String) as System.Web.Mvc.ActionResult 
            Dim callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalLoginsList)
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl)
            ExternalLoginsListOverride(callInfo, returnUrl)
            Return callInfo
        End Function

		Partial Private Sub RemoveExternalLoginsOverride(callInfo As T4MVC_System_Web_Mvc_ActionResult)

		End Sub
        Public Overrides Function RemoveExternalLogins() as System.Web.Mvc.ActionResult 
            Dim callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoveExternalLogins)
            RemoveExternalLoginsOverride(callInfo)
            Return callInfo
        End Function

    End Class

#End Region
'#pragma warning restore 1591
