'// <auto-generated />
'// This file was generated by a T4 template.
'// Don't change it directly as your change would get overwritten.  Instead, make changes
'// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

'// Make sure the compiler doesn't complain about missing Xml comments
'#pragma warning disable 1591
#region "T4MVC"

Imports System
Imports System.Diagnostics
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.Linq
Imports System.Runtime.CompilerServices
Imports System.Web
Imports System.Web.Hosting
Imports System.Web.Mvc
Imports System.Web.Mvc.Ajax
Imports System.Web.Mvc.Html
Imports System.Web.Routing
Imports .T4MVC
Namespace T4MVC
    Public Class SharedController

		Public Shared Readonly s_views as ViewsClass = new ViewsClass()
        <GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
		Public ReadOnly Property Views as ViewsClass
			Get
				Return s_views
			End Get
		End Property

		<GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode()>
		Public Class ViewsClass
            Shared ReadOnly s_ViewNames as _ViewNamesClass = new _ViewNamesClass()
            Public ReadOnly Property ViewNames as _ViewNamesClass
            	Get
            		Return s_ViewNames
            	End Get
            End Property
            
            Public Class _ViewNamesClass
                Public ReadOnly _Layout As String = "_Layout"
                Public ReadOnly _LoginPartial As String = "_LoginPartial"
                Public ReadOnly [Error] As String = "Error"
            End Class
            Public ReadOnly _Layout As String = "~/Views/Shared/_Layout.vbhtml"
            Public ReadOnly _LoginPartial As String = "~/Views/Shared/_LoginPartial.vbhtml"
            Public ReadOnly [Error] As String = "~/Views/Shared/Error.vbhtml"
        End Class
    End Class

End Namespace

#End Region
'#pragma warning restore 1591
